# Author: Kshitij Kshirsagar
# Filename: build_labeler.py
# Last edited: 07/06/2026


def calculate_gaming_score(build):
    """
    used to calculate a gaming score for a PC build
    :param build: PCBUILD object containing CPU, GPU, motherboard, RAM, storage, and PSU
    :return score: numerical gaming score based mostly on GPU performance
    """
    components = build.show_components()

    cpu = components[0]
    gpu = components[1]
    ram = components[3]
    storage = components[4]

    score = (
        gpu.g3d_mark * 0.60
        + cpu.single_thread_score * 0.20
        + cpu.cpu_mark * 0.10
        + ram.size_gb * 50
        + storage.capacity_gb * 0.5
    )

    return score


def calculate_workstation_score(build):
    """
    used to calculate a workstation score for a PC build
    :param build: PCBUILD object containing CPU, GPU, motherboard, RAM, storage, and PSU
    :return score: numerical workstation score based mostly on CPU and RAM performance
    """
    components = build.show_components()

    cpu = components[0]
    gpu = components[1]
    ram = components[3]
    storage = components[4]

    score = (
        cpu.cpu_mark * 0.55
        + cpu.cores * 800
        + ram.size_gb * 250
        + storage.capacity_gb * 0.8
        + gpu.g3d_mark * 0.10
    )

    return score


def calculate_machine_learning_score(build):
    """
    used to calculate a machine learning score for a PC build
    :param build: PCBUILD object containing CPU, GPU, motherboard, RAM, storage, and PSU
    :return score: numerical machine learning score based mostly on GPU and RAM
    """
    components = build.show_components()

    cpu = components[0]
    gpu = components[1]
    ram = components[3]
    storage = components[4]

    rtx_bonus = 5000 if "RTX" in gpu.name.upper() else 0

    score = (
        gpu.g3d_mark * 0.55
        + cpu.cpu_mark * 0.15
        + ram.size_gb * 300
        + storage.capacity_gb * 0.5
        + rtx_bonus
    )

    return score


def calculate_value_score(build, performance_score):
    """
    used to calculate performance per dollar for a PC build
    :param build: PCBUILD object containing all chosen components
    :param performance_score: score calculated from gaming, workstation, or machine learning function
    :return value_score: performance score divided by total build price
    """
    return performance_score / build.total_price()


def calculate_final_score(build, purpose="gaming"):
    """
    used to calculate final build score based on the user's purpose
    :param build: PCBUILD object containing CPU, GPU, motherboard, RAM, storage, and PSU
    :param purpose: user purpose such as gaming, workstation, or machine_learning
    :return final_score: combined score using performance and value
    """
    if purpose == "workstation":
        performance_score = calculate_workstation_score(build)
    elif purpose == "machine_learning":
        performance_score = calculate_machine_learning_score(build)
    else:
        performance_score = calculate_gaming_score(build)

    value_score = calculate_value_score(build, performance_score)

    final_score = (
        performance_score * 0.80
        + value_score * 1000 * 0.20
    )

    return final_score


def label_builds(builds, purpose="gaming"):
    """
    used to label PC builds by comparing their scores against all other generated builds
    :param builds: list of PCBUILD objects generated by the build generator
    :param purpose: user purpose such as gaming, workstation, or machine_learning
    :return labelled_builds: list of dictionaries containing build, score, and label
    """
    labelled_builds = []

    for build in builds:
        score = calculate_final_score(build, purpose)

        labelled_builds.append({
            "build": build,
            "score": score,
            "label": None
        })

    labelled_builds.sort(
        key=lambda item: item["score"],
        reverse=True
    )

    total_builds = len(labelled_builds)

    for index, item in enumerate(labelled_builds):
        percentile = index / total_builds

        if purpose == "workstation":
            if percentile <= 0.20:
                item["label"] = "High-end Workstation"
            elif percentile <= 0.60:
                item["label"] = "Mid-range Workstation"
            else:
                item["label"] = "Budget Workstation"

        elif purpose == "machine_learning":
            if percentile <= 0.20:
                item["label"] = "High-end Machine Learning Build"
            elif percentile <= 0.60:
                item["label"] = "Mid-range Machine Learning Build"
            else:
                item["label"] = "Budget Machine Learning Build"

        else:
            if percentile <= 0.20:
                item["label"] = "High-end Gaming"
            elif percentile <= 0.60:
                item["label"] = "Mid-range Gaming"
            elif percentile <= 0.90:
                item["label"] = "Budget Gaming"
            else:
                item["label"] = "Entry Level"

    return labelled_builds